# Generated by Django 4.0.5 on 2022-06-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='info',
        ),
    ]
